# Generated by Django 5.1.6 on 2025-02-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_alter_factura_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
